apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: healthcare-app
  template:
    metadata:
      labels:
        app: healthcare-app
    spec:
      containers:
      - name: my-container
        image: my-image:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8082  # Container listens on port 8080

---
apiVersion: v1
kind: Service
metadata:
  name: healthcare-app-service
spec:
  selector:
    app: healthcare-app
  ports:
    - protocol: TCP
      port: 8082         # Expose on port 8082
      targetPort: 8082   # Container listens on port 8080
  type: NodePort         # Expose using NodePort
